### PR TITLE
use django suit

### PR DESCRIPTION
**Pull request by benjaoming**
I've been using this a lot and really like it. It doesn't require any changes and doesnt break with the template logic from django.contrib.admin.

Here's how it looks:

screenshot from 2015-09-20 01 30 23

...it's free for non-commercial use.

https://github.com/darklow/django-suit

### CODE REVIEW

**Comment by valberg** [comment]
Personally I'm not a big fan of django-suit, mainly because it doesn't add enough value to be included as a dependency. Maybe you have a use case that can convince me? (I'd rather use https://github.com/elky/django-flat-theme which is going to be the default in Django 1.9)

**Comment by benjaoming** [comment]
> because it doesn't add enough value to be included as a dependency

It's a dependency of the project just, not the app itself. The thing is that it's really swappable. You can just remove it again, nothing breaks. It's like mayo for your fries, you don't have to change the fries... it'll just make them taste better.

What it adds is: Better visual layout, and a left hand side customizable menu.

I'm also replacing  `django_admin_bootstrapped` which IMO is worse than the default admin :) -- layout is really hard to navigate visually.

**Comment by valberg** [comment]
Ah yes good point about it being a project thing and not app. I still don't think that the visual layout is better, but I won't argue about it if you like it :) We just have to make sure not to tie any vital functionality to `django-suit` customizability (which would make it a dependency that we can not "just remove").

(I agree that `django_admin_bootstrapped` is awful)

**Comment by benjaoming** [comment]
Great, thanks for the feedback, I knew you'd have an opinion about this :)

**Comment by benjaoming** [comment]
Btw. did anyone in particular vouch for `django_admin_bootstrapped` or is it fine to remove it without any further ado?

**Comment by andreaslloyd** [comment]
I think Pawel just used it to get started. I'm sure it's fine to remove it.
:-)

2015-09-20 14:09 GMT+02:00 benjaoming notifications@github.com:

**Comment by benjaoming** [comment]
Cool, I'm sure everyone will enjoy a more "easy on the eye" backed :)

**Pull request merged**
