### PR TITLE
Issue 84 add multiple items to basket

### PR DESCRIPTION
**Pull request by michkoz**
Issue 84 should be fixed now :) 

Same products with the one delivery date are grouped together and only the quantity is changed .  This apply to the none delivery date as well.

### CODE REVIEW

**Comment by benjaoming** [comment]
Awesome! We should get some precommit hooks to deal with the pep8 stuff for the future :)

**Comment by michkoz** [comment]
Well it was my fault, somehow I missed it. The first pull request and I failed. Feels bad....  

Btw. is there a version with some data? So I can see what are the issues about? Today, I have some time to play around:)

**Review by benjaoming — APPROVED** [review]
Hi @michkoz - really great PR, I guess they don't come much more straight to the point of the issue addressed and with test coverage surplus.

**Comment by benjaoming** [comment]
We haven't done anything about data, I think @sepow might be playing around with FactoryBoy?

**Pull request merged**
