### PR TITLE
add settings refactor to the vagrant setup

### PR DESCRIPTION
**Pull request by benjaoming**
i haven't actually tested this because I don't use vagrant :/

### CODE REVIEW

**Comment by benjaoming** [comment]
I do not understand your suggestion? I can fix the typo, but having a `settings.local_vagrant` would imply also having a `manage_vagrant.py` or enforcing that all vagrant commands are run with `manage.py --settings=settings.local_vagrant`, this was just to keep things simple.

**Comment by pawciobiel** [comment]
It may make sense to check if the file is already there and then don't override it - just so we are on the safe side. Whatever is more convenient for you @benjaoming ; I usually export `DJANGO_SETTINGS_MODULE`.

**Comment by benjaoming** [comment]
If you look at manage.py, I've set it up to auto-create local.py so that instructions can save one step.

**Comment by pawciobiel** [comment]
@benjaoming but I'm not sure about those changes to manage.py because running it may override someones settings file. (despite the fact you could simply use `shutil.copy`)

**Comment by benjaoming** [comment]
yeah okay, I've addressed your edge case now.

**Comment by pawciobiel** [comment]
@benjaoming I wonder if it would be better to have STATIC_ROOT pointing to root of the repo `/static` as opposed to `foodnet_project/static`, what do you think?

**Comment by benjaoming** [comment]
@pawciobiel `STATIC_ROOT` is a directory that's served by the HTTP server on a deployment, so it can be anywhere you like... if you want the default to be in the parent of the project, then you do that, if you want it to by in /var/srv/foodnet/static, you can do that...

**Comment by pawciobiel** [comment]
oh sure, I just thought it would make more sense to have it in root repo so if you want to have project specific you could and also `collectstatic` woudn't override it.

**Comment by benjaoming** [comment]
I'm merging this, someone with vagrant can make further corrections :)

**Pull request merged**
