### PR TITLE
update apps, urls and templates to match dir structure

### PR DESCRIPTION
**Pull request by pawciobiel**

### CODE REVIEW

**Comment by pawciobiel** [comment]
@benjaoming I've updated payments app templates and urls to match the directory structure you have started but could't get used to having urls.py in many places so moved it to project urls. Let me know what do you think.

**Comment by samthomson** [comment]
Nice !

**Comment by benjaoming** [comment]
@pawciobiel 

Have you resolved this comment? If you wanna override certain aspects of allauth, you need your overriding url names to be in the global

``` python
-"""
-allauth urlconf where some of the views are replaced by foodnet.membership
-views.
-
-HAS TO BE INCLUDED SEPARATELY BECAUSE ALLAUTH DOESN'T SUPPORT BEING
-IN OUR FOODNET URLCONF
-
-Example:
-
-    urlpatterns = [
-        url(r'^', include('foodnet.urls', namespace='foodnet')),
-        url(r'^accounts/', include('foodnet.urls_allauth')),
-    ]
-
-"""
```

**Comment by benjaoming** [comment]
btw it seems more modular to define `eggplant_urls = [ ... ]` in the project so :+1:  for the change, just make sure that the url name `"profile"` isn't missed somewhere...

**Comment by benjaoming** [comment]
@pawciobiel you wanna like give some feedback related to your actions ? :)

**Comment by pawciobiel** [comment]
mhm, so I merged this one in and added more fixes in https://github.com/kbhff/eggplant/pull/27
You were right `account_set_password` didn't work as it should and this was not only to issues wit url resolver. Also I've changed password change slightly. I don't think I missed `profile` url.
I haven't check password reset feature/templates so not sure if that works but this is probably something separate - not related to this PR.

**Comment by benjaoming** [comment]
What I mean is that _inside_ allauth stuff you find references to 'profile', not 'eggplant:membership:profile' so you have to keep an eye out for that unless we actually managed to override all the allauth templates already.

**Comment by pawciobiel** [comment]
hmm I think we have override only some of the templates. Can you be more specific please? Is the conflict you have mention in `allauth.account.` urls or templates?

**Comment by benjaoming** [comment]
This file was deleted, thus there's no longer a `"profile"` url pointing to the membership view.

https://github.com/kbhff/eggplant/blob/3aa7227e2dbdbc071c8dc50e288a4904166b2d6b/eggplant/urls_allauth.py

**Pull request merged**
